/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2020-11-07 07:58:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.project_4.ctl.CollegeCtl;
import in.co.rays.project_4.util.DataUtility;
import in.co.rays.project_4.util.ServletUtility;
import in.co.rays.project_4.bean.RoleBean;
import in.co.rays.project_4.ctl.LoginCtl;
import in.co.rays.project_4.bean.UserBean;
import in.co.rays.project_4.ctl.ORSView;

public final class xyz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1601878666451L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("in.co.rays.project_4.ctl.ORSView");
    _jspx_imports_classes.add("in.co.rays.project_4.ctl.CollegeCtl");
    _jspx_imports_classes.add("in.co.rays.project_4.ctl.LoginCtl");
    _jspx_imports_classes.add("in.co.rays.project_4.util.DataUtility");
    _jspx_imports_classes.add("in.co.rays.project_4.bean.RoleBean");
    _jspx_imports_classes.add("in.co.rays.project_4.util.ServletUtility");
    _jspx_imports_classes.add("in.co.rays.project_4.bean.UserBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>College View</title>\r\n");
      out.write("<link href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/css/main.css\" rel=\"stylesheet\"\r\n");
      out.write("\tid=\"bootstrap-css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.4.1/js/mdb.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".log1 {\r\n");
      out.write("\tpadding-top: 5%;\r\n");
      out.write("\t/* padding-left: 30%; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hm-gradient {\r\n");
      out.write("\tbackground-image: url('");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/bg1.png');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("i.css {\r\n");
      out.write("\tborder: 2px solid #8080803b;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("\tpadding-bottom: 11px;\r\n");
      out.write("\tbackground-color: #ebebe0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hm-gradient\">\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <title>jQuery UI Datepicker - Display month &amp; year menus</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("  $( function() {\r\n");
      out.write("    $( \"#datepicker\" ).datepicker({\r\n");
      out.write("      changeMonth: true,\r\n");
      out.write("      changeYear: true,\r\n");
      out.write("      yearRange : '1970:2030'\r\n");
      out.write("    });\r\n");
      out.write("  } );\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("  $( function() {\r\n");
      out.write("    $( \"#datepicker\" ).datepicker();\r\n");
      out.write("  } );\r\n");
      out.write("  </script> -->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");

    UserBean userBean = (UserBean) session.getAttribute("user");

    boolean userLoggedIn = userBean != null;

    String welcomeMsg = "Hi, ";

    if (userLoggedIn) {
        String role = (String) session.getAttribute("role");
        welcomeMsg += userBean.getFirstName() + " (" + role + ")";
    } else {
        welcomeMsg += "Guest";
    }

      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"90%\" ><a href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\">Welcome</b></a> |\r\n");
      out.write("            ");

            if (userLoggedIn) {
        
      out.write(" <a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\">Logout</b></a>\r\n");
      out.write("\r\n");
      out.write("            ");

                } else {
            
      out.write(" <a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\">Login</b></a> ");

     }
 
      out.write("</td>\r\n");
      out.write("        <td rowspan=\"2\">\r\n");
      out.write("            \r\n");
      out.write("   \t\t<center>         \r\n");
      out.write("            <!-- <img alt=\"Ajay\" src=\"rays.png\"> -->\r\n");
      out.write("             <h1 align=\"right\">   <img src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/image/rays.png\" width=\"318\"\r\n");
      out.write("                    height=\"90\"></h1>\r\n");
      out.write("            </center>\r\n");
      out.write("        </td> \r\n");
      out.write("\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("        <td >\r\n");
      out.write("            <h3>\r\n");
      out.write("                ");
      out.print(welcomeMsg);
      out.write("</h3>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    ");

        if (userLoggedIn) {
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td colspan=\"2\" >\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\">Get Marksheet</b></a> |\r\n");
      out.write("            <a href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\">Marksheet Merit\r\n");
      out.write("                List</b>\r\n");
      out.write("        </a> | <a href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\">MyProfile</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\">Change Password</b></a>    ");

            if (userBean.getRoleId() == RoleBean.ADMIN) {
        
      out.write("| <a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\">Add Marksheet</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\">Marksheet List</b></a> |\r\n");
      out.write("            <a href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\">Add User</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\">User List</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\">Add College</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\">Add Student</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\">Add Role</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\">Role List</b></a> |<a\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\">Add Course</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\">Course List</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\">Add Subject</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\">Subject List</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\">Add TimeTable</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\">TimeTable List</b></a>| <a\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\">Add Faculty</b></a>| <a\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\">Faculty List</b></a> | <a\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(ORSView.JAVA_DOC_VIEW);
      out.write("\" target=\"blank\">Java Doc</b></a> |  ");

     }
 
      out.write("</td>\r\n");
      out.write("    \r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<hr>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t<main>\r\n");
      out.write("\t\t<form action=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row log1\">\r\n");
      out.write("\t\t\t\t<!-- Grid column -->\r\n");
      out.write("\t\t\t\t");
      in.co.rays.project_4.bean.CollegeBean bean = null;
      bean = (in.co.rays.project_4.bean.CollegeBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new in.co.rays.project_4.bean.CollegeBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 mb-4\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 mb-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								long id = DataUtility.getLong(request.getParameter("id"));

								if (id > 0) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"text-center default-text py-3\">Update College</h3>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"text-center default-text py-3\">Add College</h3>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!--Body-->\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<H4 align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if (!ServletUtility.getSuccessMessage(request).equals("")) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"alert alert-success alert-dismissible\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</H4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<H4 align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										if (!ServletUtility.getErrorMessage(request).equals("")) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"alert alert-danger alert-dismissible\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</H4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(bean.getId());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"createdBy\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(bean.getCreatedBy());
      out.write("\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"modifiedBy\" value=\"");
      out.print(bean.getModifiedBy());
      out.write("\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"hidden\" name=\"createdDatetime\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(DataUtility.getTimestamp(bean.getCreatedDateTime()));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"modifiedDatetime\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(DataUtility.getTimestamp(bean.getModifiedDateTime()));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pl-sm-5\"><b>Name</b><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red;\">*</span></span> </br> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-university prefix grey-text css\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 1rem;\"></i> <input type=\"text\" name=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"defaultForm-email\" style=\"border: 2px solid #8080803b;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(DataUtility.getStringData(bean.getName()));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=\"red\" class=\"pl-sm-5\"> ");
      out.print(ServletUtility.getErrorMessage("name", request));
      out.write("</font></br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pl-sm-5\"><b>Address</b><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red;\">*</span></span> </br> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-address-book prefix grey-text css\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 1rem;\"></i> <input type=\"text\" name=\"address\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"defaultForm-email\" style=\"border: 2px solid #8080803b;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Address\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(DataUtility.getStringData(bean.getAddress()));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=\"red\" class=\"pl-sm-5\"> ");
      out.print(ServletUtility.getErrorMessage("address", request));
      out.write("</font></br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pl-sm-5\"><b>State</b><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red;\">*</span></span> </br> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fas fa-address-card prefix grey-text\"></i> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"state\" id=\"defaultForm-email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 2px solid #8080803b;\" placeholder=\"Enter State\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(DataUtility.getStringData(bean.getState()));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=\"red\" class=\"pl-sm-5\"> ");
      out.print(ServletUtility.getErrorMessage("state", request));
      out.write("</font></br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pl-sm-5\"><b>City</b><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red;\">*</span></span> </br> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"far fa-address-card prefix grey-text css\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 1rem;\"></i> <input type=\"text\" name=\"city\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"defaultForm-email\" style=\"border: 2px solid #8080803b;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Enter City\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(DataUtility.getStringData(bean.getCity()));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=\"red\" class=\"pl-sm-5\"> ");
      out.print(ServletUtility.getErrorMessage("city", request));
      out.write("</font></br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pl-sm-5\"><b>Mobile No</b><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"color: red;\">*</span></span> </br> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-phone prefix grey-text css\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 1rem;\"></i> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"mobileNo\" placeholder=\"Enter MobileNo\" maxlength=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"border: 2px solid #8080803b;\" id=\"defaultForm-pass\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(DataUtility.getStringData(bean.getPhoneNo()));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=\"red\" class=\"pl-sm-5\"> ");
      out.print(ServletUtility.getErrorMessage("mobileNo", request));
      out.write("</font></br>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</br>\r\n");
      out.write("\t\t\t\t\t\t\t");

								if (id > 0) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"operation\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-success btn-md\" style=\"font-size: 17px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(CollegeCtl.OP_UPDATE);
      out.write("\"> <input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"operation\" class=\"btn btn-success btn-md\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 17px\" value=\"");
      out.print(CollegeCtl.OP_CANCEL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"operation\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-success btn-md\" style=\"font-size: 17px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(CollegeCtl.OP_SAVE);
      out.write("\"> <input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"operation\" class=\"btn btn-warning btn-md\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 17px\" value=\"");
      out.print(CollegeCtl.OP_RESET);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 mb-4\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
